# Probabilistic Model


In [78]:
import numpy as np

In [79]:
p_honest = 0
p_dishonest = 1 - p_honest

p_coerced = 1
p_not_coerced = 1 - p_coerced

#there is a set of defined conditional probabilities for the true_position variable.
#because these are either 0 or 1, I will add a 1 when that is the case, or not include the equation when its a 0.

In [80]:

a1 = p_dishonest * p_not_coerced * 1
b1 = 0
c1 = p_honest * p_not_coerced 
d1 = p_honest * p_coerced
e1 = p_dishonest * p_coerced * 1
f1 = 0

In [81]:
starting_state = np.array([a1, b1, c1, d1, e1, f1])

In [82]:
m11 = 0
m12 = p_dishonest * p_not_coerced * 1 
m13 = p_honest * p_not_coerced * 1
m14 = p_honest * p_coerced * 1
m15 = 0
m16 = p_dishonest * p_coerced * 1

m21 = 0
m22 = 0
m23 = 0
m24 = 0
m25 = 0
m26 = 0

m31 = 0
m32 = p_dishonest * p_not_coerced * 1
m33 = p_honest * p_not_coerced * 1
m34 = p_honest * p_coerced * 1
m35 = 0
m36 = p_dishonest * p_coerced * 1

m41 = p_dishonest * p_not_coerced * 1
m42 = 0
m43 = p_honest * p_not_coerced * 1
m44 = p_honest * p_coerced * 1
m45 = p_dishonest * p_coerced * 1
m46 = 0

m51 = p_dishonest * p_not_coerced * 1
m52 = 0
m53 = p_honest * p_not_coerced * 1
m54 = p_honest * p_coerced * 1
m55 = p_dishonest * p_coerced * 1
m56 = 0

m61 = 0
m62 = 0
m63 = 0
m64 = 0
m65 = 0
m66 = 0

In [83]:
#Probability of picking a certain child, given that you are a certain parent.
M = np.array([[m11, m12, m13, m14, m15, m16],
            [m21, m22, m23, m24, m25, m26],
            [m31, m32, m33, m34, m35, m36],
            [m41, m42, m43, m44, m45, m46],
            [m51, m52, m53, m54, m55, m56],
            [m61, m62, m63, m64, m65, m66]])

In [84]:
#Child to parent approval matrix 
A = np.array([[0, 0, 0, 1, 0, 0],
            [0, 0 , 0, 0, 0, 0],
            [0, 0, 1, 1, 0, 0],
            [1, 0, 1, 1, 1, 0],
            [0, 0, 0, 1, 1, 0],
            [0, 0, 0, 0, 0, 0]])

#note that A is symmetric
#print(A - np.transpose(A))

In [85]:
assert A.size == M.size

In [86]:
import simulator_functions as sim

total_edges = sim.edge_probabilities(starting_state, M, A, depth=1, number_of_neighbours=[6])
print(total_edges)

[0. 0. 0. 0. 6. 0.]


# For platoons

In [87]:
#initial state can be only state A, D and E, and D is 0. Because we say a platoon is comandeered by a dishonest car. 
ap1 = p_dishonest * p_not_coerced * 1
dp1 = 0
ep1 = p_dishonest * p_coerced * 1

platoon_initial_state = np.array([ap1, dp1, ep1])

In [88]:
print(len(platoon_initial_state))


3


In [89]:
#Platoon Matrix Mp

mp11 = 0
mp12 = p_honest * p_coerced * 1
mp13 = 0

mp21 = p_dishonest * p_not_coerced * 1
mp22 = p_honest * p_coerced * 1
mp23 = p_dishonest * p_coerced * 1

mp31 = p_dishonest * p_not_coerced * 1
mp32 = p_honest * p_coerced * 1
mp33 = p_dishonest * p_coerced * 1

In [90]:
Mp = np.array([[mp11, mp12, mp13],
                [mp21, mp22, mp23], 
                [mp31, mp32, mp33]])

In [91]:
#Approvals Matrix of Platoons, Ap
Ap = np.array([[0, 1, 0],
                [1, 1, 1],
                [1, 1, 1]])

In [92]:
from simulator_functions import edge_probabilities

total_platoon_edges = edge_probabilities(platoon_initial_state, Mp, Ap, depth=1, number_of_neighbours=[6])
print(total_platoon_edges)

[0. 0. 6.]


In [93]:
Pp = np.multiply(Mp, Ap)

In [94]:
print(Pp)
print(Mp)
print(Pp - Mp)

[[0 0 0]
 [0 0 1]
 [0 0 1]]
[[0 0 0]
 [0 0 1]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [95]:
#For tree of depth 2 n2

platoon_depth1_probability_approvals = np.matmul(platoon_initial_state, Pp)
platoon_depth2_probability_approvals = np.matmul(platoon_depth1_probability_approvals, Pp)

total_prob_approvals = (2*platoon_depth1_probability_approvals) + (4*platoon_depth2_probability_approvals)
total_approvals = np.sum(total_prob_approvals)
print(total_approvals)

6


In [96]:
#For tree of depth 1, n6
print(6*platoon_depth1_probability_approvals)
np.sum(6*platoon_depth1_probability_approvals)

[0 0 6]


6